languageCode = "en-us"
title = "🌯 Burritalks"

[taxonomies]
  tag = "tags"
  speaker = "speakers"

[params]
  description = "Burritalks is a list of hand picked talks about the software development, domain driven design, agile, constraint theory, and more!"
  images = ["/images/logo.png"]


[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 80

  [[related.indices]]
    name = "speakers"
    weight = 100